[general]
live_config_reload = true
working_directory = "None"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false
